import type { Metadata } from "next";
import { thicccboi, interLight } from './fonts';
import "./globals.css";
import { api } from "../../api/api";
import React, { Fragment } from "react";
import WrapperProvider from "@/components/WrapperProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathSetting = 'wp-json/wp/v2/theme-options'
  const dataSetting = await api(pathSetting)

  return (
    <html lang="en">
      <body
        className={`${thicccboi.variable} ${interLight.variable} antialiased`}
      >
      <WrapperProvider dataSetting={dataSetting}>
        {children}
      </WrapperProvider>
      </body>
    </html>
  );
}
